### ISSUE TITLE
donnie -v0.7 translation not work  

### ISSUE THREAD

**Issue by ghost** [wdehoog/donnie#8]
- translation no work, 
I think you need create a es.qm file into the translation folder, i guess that **QT_Irelease** generate files *.qm . I use sdk-buildengine-terminal then this file create automatically.

**Comment by wdehoog** [comment]
I'll look into the translation not working.

Please do not put two different subjects in one issue

**Comment by wdehoog** [comment]
It starts to work. When starting from the IDE do read this: https://together.jolla.com/question/11041/bug-qlocalesystem-returns-incorrect-locale-while-run-in-debugger/

**Comment by wdehoog** [comment]
New version is built on OBS. Please give it a try.

**Comment by ghost** [comment]
Sorry for my late reply, i have a busy day.
- I already tested the new version-obs then translation still no work.  Have you already created *.qm files from *.ts files?
What version de sdk or sailfish IDE you have installed?

**Comment by ghost** [comment]
I compiled  again with my sdk, then **translation work good & built in dependencies**  Test it https://github.com/Caballlero/donnie/releases/tag/Beta2

**Comment by wdehoog** [comment]
It seems fixed in OBS now. See commit https://github.com/wdehoog/donnie/commit/1441c1988729ec133dcf61851e803695e49d956c

**Comment by ghost** [comment]
Tested again donnie-master-obs **Translate work good** . But string line 88 "Built-in player" not come translated.

**Comment by wdehoog** [comment]
Weird. I does on my phone (switched it to es).

**Comment by ghost** [comment]
Still missing some string to be translate [ New ] [ All ]  also some in Search in: [ Creator ] [ Title ] [ Artist ] [Album ]
![captura_20171012_001](https://user-images.githubusercontent.com/24536606/31526546-8b390fa8-af95-11e7-8133-eeea2b5b9c06.png)
![captura_20171012_002](https://user-images.githubusercontent.com/24536606/31526548-9168918c-af95-11e7-8522-3e3155355441.png)

**Comment by wdehoog** [comment]
Indeed I forgot all about the search capabilities. 

Your second screenshot however shows the labels returned by the media server. As some of those are already in Spanish I guess the rest should be done by the server as well.

**Comment by wdehoog** [comment]
So is it working now? Then please close the issue.

**Comment by ghost** [comment]
Thx...

**Comment by ghost** [comment]
Still some strings to translate
![captura_20171018_002](https://user-images.githubusercontent.com/24536606/31750701-aeea7d6a-b44f-11e7-85b5-84aec42b3acb.png)
[**All the screenshot**]
![captura_20171018_001](https://user-images.githubusercontent.com/24536606/31750709-b4dad7b0-b44f-11e7-8969-f2a8fd382d5f.png)
[**Renderer**] [**Content Server**] 
![captura_20171018_003](https://user-images.githubusercontent.com/24536606/31750713-bc8949b0-b44f-11e7-9d09-42dff56fdb03.png)
[**Renderer**]

**Comment by wdehoog** [comment]
You are right. I just addressed most of them. 

The only thing is I don't think the 'thanks' section on th About page needs translation. I have removed most words from it. If you want to translate the remark that refers to yourself I think it would be appropriate to have it in spanish and not to be translatable.
So can you please translate 'testing and UI rigor' into spanish?

**Comment by ghost** [comment]
yeap. thanks.

**Comment by wdehoog** [comment]
What I meant was translating 'Carlos Gonzalez for testing and UI rigor' in the AboutPage into Spanish but not translatable. No qsTr() but just Spanish.
